 
 export const AUTH={
    UPDATE_EMAIL:"UPDATE_EMAIL",
    UPDATE_PASSWORD:"UPDATE_PASSWORD",
    UPDATE_FIRST_NAME:"UPDATE_FIRST_NAME",
    UPDATE_LAST_NAME:"UPDATE_LAST_NAME",
    UPDATE_FILE:"UPDATE_FILE",
    UPDATE_TOKEN:"UPDATE_TOKEN",
    UPDATE_USER_INFO:"UPDATE_USER_INFO",
 }

 export const PRODUCT = {
  UPDATE_PODUCT_NAME: "UPDATE_PODUCT_NAME",
  UPDATE_PRICE: "UPDATE_PRICE",
  UPDATE_DESCRIPTION: "UPDATE_DESCRIPTION",
  UPDATE_CATEGORY_ID: "UPDATE_CATEGORY_ID",
  UPDATE_PRODUCT_LIST:"UPDATE_PRODUCT_LIST",
  UPDATE_PRODUCT_INFO:"UPDATE_PRODUCT_INFO"
}

export const CATEGORIES = {
  UPDATE_CATEGORY_NAME:" UPDATE_CATEGORY_NAME",
  UPDATE_CATEGORY_ID:" UPDATE_CATEGORY_ID",
  UPDATE_CATEGORY_INFO:" UPDATE_CATEGORY_INFO",
  GET_CATEGORY_REQ:"GET_CATEGORY_REQ",
  GET_CATEGORY_SUCCESS:"GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE:"GET_CATEGORY_FAILURE"
}

export const CART = {
  UPDATE_CART_INFO:"UPDATE_CART_INFO"
}

 export const SEARCH_BAR = {
   UPDATE_SEARCH_QUERY: " UPDATE_SEARCH_QUERY",
 }

 export const ORDER={
  UPDATE_NAME:"UPDATE_NAME",
  UPDATE_EMAIL:"UPDATE_EMAIL",
  UPDATE_MOBILE:"UPDATE_MOBILE",
  UPDATE_ADRESS:"UPDATE_ADDRESS",
  UPDATE_ORDER_ITEMS:"UPDATE_ORDER_ITEMS",
  UPDATE_ORDER_INFO:"UPDATE_ORDER_INFO",
}